name: Release Terminal Binaries

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_target: [PROD]

    environment: ${{ matrix.env_target }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install CGO and cross-compilation dependencies
        run: |
          sudo dpkg --add-architecture amd64
          sudo apt-get update
          sudo apt-get install -y \
            g++-x86-64-linux-gnu \
            libc6-dev-amd64-cross \
            gcc \
            libjpeg-dev:amd64 \
            libx11-dev \
            xorg-dev \
            libxtst-dev \
            xsel \
            xclip \
            libpng++-dev \
            xcb \
            libxcb-xkb-dev \
            x11-xkb-utils \
            libx11-xcb-dev \
            libxkbcommon-x11-dev \
            libxkbcommon-dev

      - name: Generate .env for ${{ matrix.env_target }}
        run: |
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "PUSHER_ID=${{ secrets.PUSHER_ID }}" >> .env
          echo "PUSHER_KEY=${{ secrets.PUSHER_KEY }}" >> .env
          echo "PUSHER_SECRET=${{ secrets.PUSHER_SECRET }}" >> .env
          echo "PUSHER_CLUSTER=${{ secrets.PUSHER_CLUSTER }}" >> .env

      - name: Set env variable for GoReleaser
        run: echo "ENV_TARGET=${{ matrix.env_target }}" >> $GITHUB_ENV

      - name: Run GoReleaser (Snapshot Build)
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.26.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV: ${{ matrix.env_target }}
          
      - name: Bump version and create tag
        id: tag_version
        uses: anothrnick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: terminal-${{ matrix.env_target }}-archive
          path: terminal_*.tar.gz

